# Generated by Django 6.0.6 on 2026-06-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_sellerorder_created_at_alter_sellerorder_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerorder',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
